### ISSUE TITLE
Create Card data model

### ISSUE THREAD

**Issue by nickzou** [nickzou/unisleevr#11]

**Comment by dazu1990** [comment]
Notable lessons from cdhrec:

- don't forget to account for double sided cards
- If the card is a commander it might have a partner or background
- we can source images from scryfall api or gatherer rather than store ourselves
- useful resource https://mtgjson.com/
- storing colour identity is key

**Comment by dazu1990** [comment]
Question for the task itself:

- Is this data model for a card in the shared card pool?
- does this task include the data model for a commander deck?

**Comment by dazu1990** [comment]
so your imagining the end state being like:
table 1 (card data)-  all card objects that get uploaded to the app with reference ids 
table 2 (deck data) - all deck objects - an individual deck will reference a userID, 1-2 cardIDs for the commander, and several cardIDs for it's shared cards
table 3 (shared pool data) - all shared pools - an individual card pool will reference userID and all cardIDs for that pool
table 4 (user data) - all users - userID, profile data, sharedpoolID, deckIDs

and this git issue is specifically for the creation of the card data (table 1) 

is that correct?

**Comment by nickzou** [comment]
Yeah, that's mostly how I'm imagining it.

A couple of things.

Half the stuff in table 4 here has already been provisioned by Laravel (Breeze) so this could just be a pure relational table.

Had a discussion on Sunday. He wants to put table 2 as an attribute of the user model. I feel like that's not how this is done. In my mind the deck is an independent model with an attribute of owner, which is has the user ID. But since I don't have enough back-end experience, I can't articulate why deck being an attribute of the user model is bad. It just feels wrong to me.

**Comment by dazu1990** [comment]
let me see if I can articulate it - From my experience at WS there are a few reasons why you don't do this:

1. **security**: you typically don't want to mix security levels in the same API endpoint without encryption. Decks are low risk where as user model will likely contain password info and more. I can expand more on this later if needed.
2. **DX and general readability**: you want the data types for the tables to be focused.  If we expand features for the app in the future and start to include addition profile info (i.e. PPI, location, paid tier etc) or additional deck info (i.e. format, budget, color identity, win ratio etc) that will lead to a very confused table. It's not intuitive to fetch the budget of a individual deck from the same place you fetch a users country of origin
3. **similar to point 2 - you have to delineate somewhere**. If you combine the deck table with the user table, why not add the shared pool etc. I typically follow the rule of if the complexity is two layers deep switch to a reference - i.e. `tableA = [{prop1: 1, prop2: [a,b,c] }]` is okay but `tableB = [{prop1: 1, prop2: [{prop1: a, prop2: [a,b,c]}, {prop1: a, prop2: [a,b,c]}, {prop1: a, prop2: [a,b,c]} ]` is not okay
4. **scaleability** - as you add features to a product, you want your data to be as flexible as possible. For example if we need overall stats on decks or pools or individual cards, it's helpful that the tables are already separated  instead of needing to filter "fetch all users but extract all the decks to join to a master array"

**Comment by nickzou** [comment]
Thank you for articulating what I think I knew but couldn't put into words.
